[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Reflection.AssemblyTitle("sxq-sdk-csharp")]
[assembly: System.Reflection.AssemblyDescription("sxqian sdk csharp")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("sxqian.com")]
[assembly: System.Reflection.AssemblyProduct("sxq-sdk-csharp")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2020")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("b76e2b75-72a8-4646-a2ef-fb1ba58de5c5")]
[assembly: System.Reflection.AssemblyFileVersion("0.1.0.0")]